insert into tb_acao(ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (ACAO_SEQ.NEXTVAL, 'FALAR', 'APERTE L1 E L2 PARA FALAR', '1');
insert into tb_acao(ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (ACAO_SEQ.NEXTVAL, 'ANDAR', 'APERTE SETA PARA DIREITA E PARA ESQUERDA PARA ANDAR', '1');
insert into tb_acao(ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (ACAO_SEQ.NEXTVAL, 'NADAR', 'APERTE L1 + SETA PRA CIMA PARA NADAR', '0');
insert into tb_acao(ID_ACAO, NOME, DESCRICAO, ATIVO) VALUES (ACAO_SEQ.NEXTVAL, 'SENTAR', 'APERTE PARA CIMA E PARA BAIXO PARA SENTAR', '0');

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS'


insert into tb_execucao(ID_EXECUCAO,ID_ACAO, DATA_EXECUCAO) VALUES (EXECUCAO_SEQ.NEXTVAL,1, TO_DATE(nvl('','03/12/2077 17:07:00'),'DD/MM/YYYY HH24:MI:SS'));
insert into tb_execucao(ID_EXECUCAO,ID_ACAO, DATA_EXECUCAO) VALUES (EXECUCAO_SEQ.NEXTVAL,2, TO_DATE(nvl('','20/08/2022 21:50:00'),'DD/MM/YYYY HH24:MI:SS'));
insert into tb_execucao(ID_EXECUCAO,ID_ACAO, DATA_EXECUCAO) VALUES (EXECUCAO_SEQ.NEXTVAL,3, TO_DATE(nvl('','22/09/2020 22:50:00'),'DD/MM/YYYY HH24:MI:SS'));
insert into tb_execucao(ID_EXECUCAO,ID_ACAO, DATA_EXECUCAO) VALUES (EXECUCAO_SEQ.NEXTVAL,4, TO_DATE(nvl('','20/11/2019 15:30:00'),'DD/MM/YYYY HH24:MI:SS'));






